/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author UNKNOWN'PC
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        lautLB = new javax.swing.JLabel();
        pantaiLB = new javax.swing.JLabel();
        gunungLB = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        gunungBT = new javax.swing.JButton();
        pantaiBT = new javax.swing.JButton();
        lautBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Penampil Gambar Button FullScreen");

        imagePanel.setAlignmentX(1.0F);
        imagePanel.setAlignmentY(1.0F);
        imagePanel.setLayout(new java.awt.CardLayout());

        lautLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lautLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/lautt.jpg"))); // NOI18N
        lautLB.setToolTipText("null");
        lautLB.setMinimumSize(new java.awt.Dimension(316, 400));
        lautLB.setName("null"); // NOI18N
        lautLB.setPreferredSize(new java.awt.Dimension(316, 400));
        lautLB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imagePanel.add(lautLB, "2");
        lautLB.getAccessibleContext().setAccessibleName("2");

        pantaiLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pantaiLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/pantai.jpg"))); // NOI18N
        pantaiLB.setMaximumSize(new java.awt.Dimension(316, 400));
        pantaiLB.setMinimumSize(new java.awt.Dimension(316, 400));
        pantaiLB.setName("null"); // NOI18N
        pantaiLB.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(pantaiLB, "1");
        pantaiLB.getAccessibleContext().setAccessibleName("0");

        gunungLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gunungLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/gunung.jpg"))); // NOI18N
        gunungLB.setToolTipText("null");
        gunungLB.setName("null"); // NOI18N
        imagePanel.add(gunungLB, "0");
        gunungLB.getAccessibleContext().setAccessibleName("1");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        gunungBT.setText("Gunung");
        gunungBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gunungBTActionPerformed(evt);
            }
        });
        buttonPanel.add(gunungBT);

        pantaiBT.setText("Pantai");
        pantaiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantaiBTActionPerformed(evt);
            }
        });
        buttonPanel.add(pantaiBT);

        lautBT.setText("Laut");
        lautBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lautBTActionPerformed(evt);
            }
        });
        buttonPanel.add(lautBT);

        exitBT.setText("Exit");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        buttonPanel.add(exitBT);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gunungBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gunungBTActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_gunungBTActionPerformed

    private void pantaiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantaiBTActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_pantaiBTActionPerformed

    private void lautBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lautBTActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_lautBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullScreen FullFrame = new PilihGambarButtonFullScreen();
            
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(FullFrame);
                
                FullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitBT;
    private javax.swing.JButton gunungBT;
    private javax.swing.JLabel gunungLB;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton lautBT;
    private javax.swing.JLabel lautLB;
    private javax.swing.JButton pantaiBT;
    private javax.swing.JLabel pantaiLB;
    // End of variables declaration//GEN-END:variables
}
